version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:artful
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y cmake libapt-pkg-dev shunit2 debian-archive-keyring apt-utils
      - run:
          name: Build
          command: |
            mkdir build
            cd build
            cmake -DAPTC_BINDIR=$(pwd)/cmd -DAPTC_LIBDIR=$(pwd)/dpkg ..
            make
      - run:
          name: Test
          command: |
            cd test/integration/
            ./test-command.sh
