include(FindPackageHandleStandardArgs)

SET(APT_BINARY_DIR ${PROJECT_BINARY_DIR}/apt)
FILE(MAKE_DIRECTORY ${APT_BINARY_DIR})

EXECUTE_PROCESS(
	COMMAND ln -s /usr/lib/x86_64-linux-gnu/libapt-private.so.0.0 libapt-private.so
	WORKING_DIRECTORY ${APT_BINARY_DIR})

FIND_PATH( APT_PKG_INCLUDE_DIR apt-pkg/init.h  )

FIND_LIBRARY(APT_PKG_LIB NAMES apt-pkg )
FIND_LIBRARY(APT_INST_LIB NAMES apt-inst )
FIND_LIBRARY(APT_PRIVATE_LIB NAMES apt-private HINTS ${APT_BINARY_DIR})

SET(APT_LIBS ${APT_PKG_LIB} ${APT_INST_LIB} ${APT_PRIVATE_LIB})

find_package_handle_standard_args(AptPkg DEFAULT_MSG APT_LIBS APT_PKG_INCLUDE_DIR)
